import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Minter from '../components/minter'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Something Cool!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mobile Native Web3, only on <a href="https://solana.com/" rel="noopener noreferrer" target="_blank">Solana!</a>
        </h1>

        <p className={styles.description}>
        What if we could Mint Solana NFTs completely Free, GASLESS & Mobile Native way? without even need
        for a chunky Desktop or hassle for a second screen! Get started by scaning this QR Code with mobile wallets or just click on the below button!{' '}
          <code className={styles.code}>(on Devnet)</code><br/>

        </p>
        
      <Minter/>
      
      <p className={styles.des} >  Follow us on {' '}
         <a href="https://twitter.com/candypay/" rel="noopener noreferrer" target="_blank">Twitter!</a> <code className={styles.code}>#SolanaSummerCamp</code> we are coming!</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://solanapay.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/solpay.svg" alt="Solpay Logo" width={62} height={25} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
